"""
PHASE 4: Authentication routes.
- POST /auth/callback: OAuth 2.0 callback (code exchange)
- POST /auth/refresh: Refresh access token
- POST /auth/logout: Logout and invalidate tokens

Never logs tokens or sensitive data.
Includes rate limiting to prevent brute force attacks.
"""

from fastapi import APIRouter, HTTPException, status, Request, Depends
from typing import Optional
from pydantic import BaseModel
from app.auth.token_service import get_token_service
from app.auth.jwt_validator import get_jwt_validator
from app.middleware.auth_middleware import require_auth, AuthContext
from app.middleware.rate_limiter import limiter
import logging

router = APIRouter(prefix="/auth", tags=["auth"])
logger = logging.getLogger(__name__)


class TokenExchangeRequest(BaseModel):
    """OAuth 2.0 callback request (PKCE)."""

    code: str
    code_verifier: str
    redirect_uri: str


class RefreshTokenRequest(BaseModel):
    """Refresh token request."""

    refresh_token: str  # encrypted


class TokenResponse(BaseModel):
    """Token response (never includes refresh_token to frontend)."""

    access_token: str
    expires_in: int
    token_type: str


class AuthCallbackResponse(BaseModel):
    """Auth callback response with encrypted refresh token for storage."""

    access_token: str
    refresh_token: str  # encrypted, server-side only
    expires_in: int
    token_type: str


@router.post("/callback", response_model=AuthCallbackResponse)
@limiter.limit("5/minute")  # Rate limit: 5 calls per minute (sensitive endpoint)
async def auth_callback(request: Request, token_request: TokenExchangeRequest) -> AuthCallbackResponse:
    """
    OAuth 2.0 callback: Exchange authorization code for tokens.
    
    Request:
        - code: authorization code from PingOne
        - code_verifier: PKCE code verifier (generated by Flutter)
        - redirect_uri: must match registered redirect URI
    
    Response:
        - access_token: JWT for API calls
        - refresh_token: encrypted, client stores for later refresh
        - expires_in: 28800 seconds (8 hours)
        - token_type: "Bearer"
    
    Never logs code or tokens.
    Fail-closed: any error returns 400.
    """
    try:
        token_service = await get_token_service()

        # Exchange code for tokens
        tokens = await token_service.exchange_code_for_tokens(
            code=token_request.code,
            code_verifier=token_request.code_verifier,
            redirect_uri=token_request.redirect_uri,
        )

        if not tokens:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Code exchange failed",
            )

        # Validate access token
        validator = await get_jwt_validator()
        claims = await validator.validate(tokens["access_token"])
        if not claims:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Invalid access token",
            )

        logger.info("auth_callback", extra={"user_id": claims.get("user_id")})

        return AuthCallbackResponse(
            access_token=tokens["access_token"],
            refresh_token=tokens["refresh_token"],
            expires_in=tokens["expires_in"],
            token_type=tokens["token_type"],
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error("auth_callback_error", extra={"error": str(e)})
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Authorization failed",
        )


@router.post("/refresh", response_model=TokenResponse)
@limiter.limit("10/minute")  # Rate limit: 10 calls per minute
async def refresh_token(request: Request, refresh_request: RefreshTokenRequest) -> TokenResponse:
    """
    Refresh access token using refresh token.
    
    Request:
        - refresh_token: encrypted refresh token
    
    Response:
        - access_token: new JWT
        - expires_in: 28800 seconds
        - token_type: "Bearer"
    
    New refresh_token is NOT returned (client stores encrypted token locally).
    Never logs tokens.
    """
    try:
        token_service = await get_token_service()

        # Refresh tokens
        tokens = await token_service.refresh_access_token(
            encrypted_refresh_token=refresh_request.refresh_token
        )

        if not tokens:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Refresh failed",
            )

        # Validate new access token
        validator = await get_jwt_validator()
        claims = await validator.validate(tokens["access_token"])
        if not claims:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid refreshed token",
            )

        logger.info("refresh_token", extra={"user_id": claims.get("user_id")})

        return TokenResponse(
            access_token=tokens["access_token"],
            expires_in=tokens["expires_in"],
            token_type=tokens["token_type"],
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error("refresh_token_error", extra={"error": str(e)})
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh failed",
        )


@router.post("/logout", response_model=dict)
@limiter.limit("10/minute")  # Rate limit: 10 calls per minute
async def logout(request: Request, auth: AuthContext = Depends(require_auth)) -> dict:
    """
    Logout: Invalidate tokens and clear session.
    Requires valid Bearer token.
    
    Response:
        - status: "success"
    
    Never logs tokens.
    """
    try:
        user_id = auth.user_id
        # In Supabase, delete/invalidate tokens stored for this user
        # (handled in database setup step)

        logger.info("logout", extra={"user_id": user_id})

        return {"status": "success"}

    except Exception as e:
        logger.error("logout_error", extra={"error": str(e)})
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Logout failed",
        )
